### PR TITLE
Allow for generation of gem via Rake target 'gem'

### PR DESCRIPTION
**Pull request by 2maz**

### CODE REVIEW

**Comment by doudou** [comment]
I know it's more work ... but it would be better in the long run to standardize on 'build', which is the default bundler target a.k.a. a very widely used thing.

I'm merging that one anyways

**Comment by 2maz** [comment]
Thx, I will keep that in mind for the next iteration.

**Comment by doudou** [comment]
Especially since I'm moving anything I can turn into a gem to bundler... much smoother experience than hoe (and much better for travis)

**Comment by 2maz** [comment]
We are using a fallback mechanism for rake targets to do the gem creation in this order: 'gem','dist:gem','build'. If there are others to consider just let me know.

**Pull request merged**
